#!/usr/bin/env bash

## Compare Semantic Versions
#
# param 1 - required = old semantic version
# param 2 - required = new semantic version
# param 3 - optional = indicate which levels of semantic
#                      version needs to be compared
compare_semantic_version(){
	local oldVersion=$1 newVersion=$2
  local maxDepth=${3:-3}

	# Check all versions
	for i in $(seq $maxDepth);
		do
		local oldPartVersion=$(echo $oldVersion | cut -d'.' -f"$i");
		local newPartVersion=$(echo $newVersion | cut -d'.' -f"$i");

		if is_newer_version $oldPartVersion $newPartVersion;
		then
			return 0;
		fi
	done

	return 1
}

is_newer_version(){
	local oldVersion=$1 newVersion=$2

	if [ $newVersion -gt $oldVersion ]
	then
	 return 0;
	fi

	return 1;
}
